version: 0.9.{build}
image: Visual Studio 2017
configuration: Release
platform: x64

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - set BUILD_DIR=%cd%
    - cd ..
    - curl -O http://luajit.org/download/LuaJIT-2.0.5.zip
    - unzip LuaJIT-2.0.5.zip
    - cd LuaJIT-2.0.5\src
    - msvcbuild
    - set LUAJIT_DIR=c:\projects\LuaJIT-2.0.5\src
    - cd %BUILD_DIR%
    - cmake -DCMAKE_GENERATOR_PLATFORM=x64 .
    - msbuild Project.sln
    - dir /s c:\projects\love-imgui

test: off

artifacts:
    - path: Release\imgui.dll
      name: love-imgui-win64.dll

deploy:
    provider: GitHub
    auth_token:
        secure: QAwjfXBfk1n/gpJs1AfMe/VLAc3N6PbVOxe9yjLg0I3hVnH6pJXEWzLV5/iwuCKK
    release: $(appveyor_repo_branch)-latest
    description: 'love-imgui-latest'
    prerelease: true
    artifact: /.*\.dll/
