version: 0.9.{build}
image: Visual Studio 2017
configuration: Release

platform: x64

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - set BUILD_DIR=%cd%
    - cd ..
    - curl -O http://luajit.org/download/LuaJIT-2.0.5.zip
    - unzip LuaJIT-2.0.5.zip
    - cd LuaJIT-2.0.5\src
    - msvcbuild
    - set LUAJIT_DIR=c:\projects\LuaJIT-2.0.5\src
    - cd %BUILD_DIR%
    - cmake .
    - dir /s c:\projects\love-imgui
    - git status

test: off

artifacts:
    - path: "*"
      name: Release
      type: zip

deploy:
    provider: GitHub
    auth_token:
        secure: 0h1+FjAtYe4Q6io/1tKnoEBalYWLfvG0QsqVVF5aq8SVgYGIXA31VAA8rT7gEI3q
    release: latest
    description: 'Imgui latest build'
    prerelease: true
    artifact: /.*\.dll)+/
    on:
        branch: master
