name: love-imgui

on: [push, pull_request]

jobs:
  build-win32:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]
    steps:
    - name: Shallow Clone LuaJIT
      shell: cmd
      run: git clone --depth 1 https://github.com/LuaJIT/LuaJIT
    - name: Build LuaJIT
      shell: cmd
      env:
        BUILD_ARCH: ${{ matrix.arch }}
      run: |
        rem GitHub actions where's my VS2017 vcvarsall.bat?
        set VCBT="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        if %BUILD_ARCH% == Win32 (
          call %VCBT% x86
        ) else (
          call %VCBT% x86_amd64
        )
        cd LuaJIT\src
        msvcbuild amalg
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: love-imgui
    - name: Checkout submodules
      shell: cmd
      run: |
        cd love-imgui
        git submodule update --init --recursive
    - name: Configure
      shell: cmd
      env:
        BUILD_ARCH: ${{ matrix.arch }}
      run: |
        set LUAJIT_DIR=%CD%\LuaJIT\src
        cmake -Bbuild -Himgui-bindings -T v141 -A %BUILD_ARCH% -DEnableWren=OFF -DCMAKE_INSTALL_PREFIX=%CD%\installdir
    - name: Build
      shell: cmd
      run: cmake --build build --config Release --target install
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: love-imgui-windows-${{ matrix.arch }}
        path: installdir/lib
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Get Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libluajit-5.1-dev luajit libsdl2-dev libvulkan-dev --assume-yes
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: love-imgui
    - name: Checkout submodules
      shell: bash
      run: |
        cd love-imgui
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Configure
      run: cmake -Bbuild -Hlove-imgui -DCMAKE_INSTALL_PREFIX=$PWD/installdir -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --target install
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: love-imgui-linux
        path: installdir/lib

